export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/',
  EMPLOYEES: '/employees',
  DOCUMENTS: '/documents',
  TEMPLATES: '/templates',
  TIME: '/time',
  ABSENCES: '/absences',
  LEAVES: '/leaves',
  SETTINGS: '/settings',
  USERS: '/users',
  WORK_SCHEDULES: '/work-schedules',
  PUBLIC_HOLIDAYS: '/public-holidays',
  AUDIT_LOGS: '/audit-logs',
  FORGOT_PASSWORD: '/forgot-password',
  EMPLOYEE_CREATE: '/employees/create',
  EMPLOYEE_DETAIL: '/employees/:id',
  TEMPLATE_EDITOR: '/templates/:id',
  TEMPLATE_EDITOR_NEW: '/templates/new',
  TEMPLATE_EDITOR_EDIT: '/templates/:id/edit',
  GENERATE_DOCUMENT: '/documents/generate',
  EMPLOYEE_TIME: '/time/:id',
  ABSENCE_DETAIL: '/absences/:id',
  LEAVE_REQUEST: '/leaves/request',
  LEAVE_TYPES: '/leave-types',
  DOCUMENT_VIEW: '/documents/:id/view',
};
